$(document).ready(function()
{
    $('[name=fullScreen]').click(function()
    {
        if($('#fullScreen2').prop('checked'))
        {
            $('.chapter').show();
        }
        else
        {
            $('.chapter').hide();
        }
    })
})
